[PHP]
extension_dir = "C:\Program Files\php\ext"
extension = php_pdo_pgsql.dll
extension = php_pgsql.dll
extension = php_fileinfo.dll
extension = php_zip.dll
extension = php_openssl.dll
curl.cainfo = "C:/Program Files/Git/usr/ssl/certs/ca-bundle.crt"
openssl.cafile = "C:/Program Files/Git/usr/ssl/certs/ca-bundle.crt"
